# Generated by Django 2.2 on 2020-08-24 15:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contest_name', models.CharField(max_length=100)),
                ('contest_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contest',
            },
        ),
        migrations.CreateModel(
            name='ContestGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='contest group name', unique=True)),
                ('type', models.CharField(choices=[('Prelims', 'Prelims'), ('Finals', 'Finals')], help_text='contest type', max_length=100)),
                ('country', models.CharField(choices=[('India', 'India'), ('US', 'US')], help_text='country type', max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contest_group',
            },
        ),
        migrations.CreateModel(
            name='WordBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexicographical', models.CharField(blank=True, max_length=1, null=True)),
                ('word', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=100)),
                ('land_of_origin', models.CharField(max_length=100)),
                ('additional_info', models.CharField(max_length=3000)),
                ('sentence', models.CharField(blank=True, max_length=3000, null=True)),
                ('spellbee_type', models.CharField(choices=[('JSB', 'JSB'), ('SSB', 'SSB')], max_length=100)),
                ('phase', models.CharField(choices=[('Phase 1', 'Phase 1'), ('Phase 2', 'Phase 2')], max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('file_name_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name_sentence', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name_complete', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name_definition', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'word_bank',
            },
        ),
        migrations.CreateModel(
            name='WordReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='unavailable', max_length=100)),
                ('pronunciation', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='unavailable', max_length=100)),
                ('pos', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='unavailable', max_length=100)),
                ('land_of_origin', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='unavailable', max_length=100)),
                ('additional_info', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='unavailable', max_length=100)),
                ('sentence', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='unavailable', max_length=100)),
                ('spellbee_type', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='unavailable', max_length=100)),
                ('phase', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='unavailable', max_length=100)),
                ('year', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='unavailable', max_length=100)),
                ('difficulty_level', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='unavailable', max_length=100)),
                ('file_name', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('incomplete', 'incomplete'), ('low_voice', 'low_voice'), ('noise', 'noise'), ('not_clear', 'not_clear'), ('not_playing', 'not_playing'), ('repeating', 'repeating')], default='unavailable', max_length=100)),
                ('file_name_origin', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('incomplete', 'incomplete'), ('low_voice', 'low_voice'), ('noise', 'noise'), ('not_clear', 'not_clear'), ('not_playing', 'not_playing'), ('repeating', 'repeating')], default='unavailable', max_length=100)),
                ('file_name_sentence', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('incomplete', 'incomplete'), ('low_voice', 'low_voice'), ('noise', 'noise'), ('not_clear', 'not_clear'), ('not_playing', 'not_playing'), ('repeating', 'repeating')], default='unavailable', max_length=100)),
                ('file_name_complete', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('incomplete', 'incomplete'), ('low_voice', 'low_voice'), ('noise', 'noise'), ('not_clear', 'not_clear'), ('not_playing', 'not_playing'), ('repeating', 'repeating')], default='unavailable', max_length=100)),
                ('file_name_definition', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('incomplete', 'incomplete'), ('low_voice', 'low_voice'), ('noise', 'noise'), ('not_clear', 'not_clear'), ('not_playing', 'not_playing'), ('repeating', 'repeating')], default='unavailable', max_length=100)),
                ('file_name_remarks', models.TextField(blank=True)),
                ('file_name_origin_remarks', models.TextField(blank=True)),
                ('file_name_sentence_remarks', models.TextField(blank=True)),
                ('file_name_complete_remarks', models.TextField(blank=True)),
                ('file_name_definition_remarks', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('deleted', 'deleted'), ('incomplete', 'incomplete'), ('verified', 'verified'), ('open', 'open')], default='open', max_length=100)),
                ('is_dirty', models.BooleanField(default=False)),
                ('modified_by', models.CharField(default='', max_length=100)),
                ('modified_on', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('word_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_bank', to='core.WordBank')),
            ],
            options={
                'db_table': 'word_review',
            },
        ),
        migrations.CreateModel(
            name='WordContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField(default='[]')),
                ('spellbee_type', models.CharField(choices=[('JSB', 'JSB'), ('SSB', 'SSB')], max_length=100)),
                ('phase', models.CharField(choices=[('Phase 1', 'Phase 1'), ('Phase 2', 'Phase 2'), ('Finals', 'Finals')], max_length=100)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_contest', to='core.Contest')),
            ],
            options={
                'db_table': 'word_contest',
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest', to='core.ContestGroup'),
        ),
    ]
