# Generated by Django 2.2 on 2020-08-24 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200824_2238'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordcontest',
            unique_together=set(),
        ),
    ]
