# Generated by Django 2.2 on 2020-08-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200824_2246'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestgroup',
            unique_together=set(),
        ),
    ]
