# Generated by Django 2.2 on 2020-08-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200826_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('loaded', 'loaded')], default='new', help_text='contest status', max_length=100),
        ),
    ]
