# Generated by Django 2.2 on 2020-08-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='status',
        ),
        migrations.AddField(
            model_name='wordbank',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('loaded', 'loaded')], default='new', help_text='contest status', max_length=100),
        ),
    ]
