# Generated by Django 2.2 on 2020-08-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200828_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordbank',
            name='status',
        ),
        migrations.AddField(
            model_name='wordcontest',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('loaded', 'loaded')], default='new', help_text='contest status', max_length=100),
        ),
    ]
