# Generated by Django 2.2 on 2020-08-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
